version: '3.8'

services:
  cassandra:
    image: cassandra:4.0.9
    container_name: cassandra
    logging:
      driver: none
    ports:
      - "9042:9042"
    networks:
      - cassandra
    environment:
      CASSANDRA_START_RPC: 'true'
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./conf/cassandra.yaml:/etc/cassandra/cassandra.yaml

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-app
    depends_on:
      - cassandra
    networks:
      - cassandra
    ports:
      - "8080:8080/tcp"
      - "3000:3000/tcp"
    environment:
      CASSANDRA_HOST: cassandra
    stdin_open: true
    tty: true
    command: ["bash"]
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/target
      - .:/server_data/

volumes:
  cassandra_data:

networks:
  cassandra:
    driver: bridge
