version: '3.8'

services:
  cassandra:
    image: cassandra:4.0.9
    container_name: cassandra
    ports:
      - "9042:9042"
    networks: 
      - cassandra 
    environment:
      CASSANDRA_START_RPC: 'true'
    volumes:
      - cassandra_data:/var/lib/cassandra
    logging:
      driver: "none"

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-app
    depends_on:
      - cassandra
    networks: 
      - cassandra 
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      CASSANDRA_HOST: cassandra
    command: ["./target/release/PPgram-api"]

volumes:
  cassandra_data:

networks:
  cassandra:
    driver: bridge
