services:
  scylla-node:
      container_name: scylla-node
      image: scylladb/scylla:5.2.0
      restart: always
      ports:
        - "9042:9042"
      networks:
        - cassandra
      volumes:
        - ./conf/scylla.yaml:/etc/scylla/scylla.yaml
        - scylla_data:/var/lib/scylla
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-app
    depends_on:
      - scylla-node
    networks:
      - cassandra
    ports:
      - "8080:8080/tcp"
      - "3000:3000/tcp"
    environment:
      CASSANDRA_HOST: 172.18.0.2
    stdin_open: true
    tty: true
    command: ["bash"]
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/target
      - ./server_data/:/server_data/
      - ./log/:/tmp/log/

networks:
  cassandra:
    driver: bridge

volumes:
  scylla_data:
